USE [master]
GO

/****** Object:  Database [CopaDoMundo]    Script Date: 07/10/2018 20:27:58 ******/
CREATE DATABASE [CopaDoMundo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CopaDoMundo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CopaDoMundo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CopaDoMundo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CopaDoMundo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CopaDoMundo] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CopaDoMundo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CopaDoMundo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CopaDoMundo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CopaDoMundo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CopaDoMundo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CopaDoMundo] SET ARITHABORT OFF 
GO

ALTER DATABASE [CopaDoMundo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CopaDoMundo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CopaDoMundo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CopaDoMundo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CopaDoMundo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CopaDoMundo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CopaDoMundo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CopaDoMundo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CopaDoMundo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CopaDoMundo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CopaDoMundo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CopaDoMundo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CopaDoMundo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CopaDoMundo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CopaDoMundo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CopaDoMundo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CopaDoMundo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CopaDoMundo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CopaDoMundo] SET  MULTI_USER 
GO

ALTER DATABASE [CopaDoMundo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CopaDoMundo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CopaDoMundo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CopaDoMundo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CopaDoMundo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CopaDoMundo] SET QUERY_STORE = OFF
GO

USE [CopaDoMundo]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CopaDoMundo] SET  READ_WRITE 
GO


