//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopaDoMundo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogos
    {
        public int JogoId { get; set; }
        public int SelecaoId1 { get; set; }
        public int SelecaoId2 { get; set; }
        public int Gol1 { get; set; }
        public int Gol2 { get; set; }
        public int FaseId { get; set; }
    
        public virtual Fases Fas { get; set; }
        public virtual Selecoes Seleco { get; set; }
        public virtual Selecoes Seleco1 { get; set; }
    }
}
